@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=bookings

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTNjYmRmMy1jMThlLTQzMjUtYmI3My1jMDgyMTBhNmRlN2YiLCJpYXQiOjE2NjA1NTY0MTUsImV4cCI6MTY2MDU2MzYxNX0.yDGyG2Ej-2njAF-vA83x3akFe3aIpSy9sEDMJkOclTE


### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=5&skip=0&include=additionalServiceItems,customer&orderBy=createdAt
content-type: application/json
authorization: Bearer {{ACCESS_TOKEN}}


### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?include=additionalServiceItems,customer,vehicle    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "customerId": "edb54b27-b7ca-4571-b984-b02efb193172",
    "vehicleId": "f6731503-72ae-4bd3-a5c6-dd238d02e78d",
    "from": "2022-07-13T17:58:37.493Z",
    "to": "2022-08-13T17:58:37.493Z",
    "duration": 30,
    "notes": "Do not forget to bring your keys",
    "additionalServiceItems": [
        {
            // Charge Battery id
            "serviceId": "db7db4fe-b924-4659-a8bd-7861d9402cec",
            "quantity": 5,
            "discount": 0
        },
        {
            // Premium polish id
            "serviceId": "8efd20d7-a06b-4484-b6e2-8d809c025e50",
            "quantity": 5,
            "discount": 0
        }
    ]
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/76d038e4-698a-4a92-bf78-d04d5add6bec
    ?include=bookings    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "firstName": "John Update",
    "lastName": "Doe Update",
    "phone": "123456789444",
    "address": "123 Main St"
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/f202a506-f91b-4e1b-bf77-88fad711e96d  
content-type: application/json