@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=bookings

### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=5&skip=0&include=services,customer&orderBy=createdAt
content-type: application/json


### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    # ?include=services,customer,vehicle    
content-type: application/json

{
    "customerId": "da574263-10b0-4aa0-adf7-e2408cca397c",
    "vehicleId": "b73fa6bb-1c60-40dc-a7a1-a89fa91581f6",
    "from": "2022-07-13T17:58:37.493Z",
    "to": "2022-08-13T17:58:37.493Z",
    "duration": 30,
    "notes": "Do not forget to bring your keys",
    "serviceIds": [
        // basic service id
        "b7e8ba53-96d7-43e9-8090-87108d1e72ec",
        "a0c8f602-a278-489a-ad3d-1b3b4112cbdd"
    ]
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/76d038e4-698a-4a92-bf78-d04d5add6bec
    ?include=bookings    
content-type: application/json

{
    "firstName": "John Update",
    "lastName": "Doe Update",
    "phone": "123456789444",
    "address": "123 Main St"
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/f202a506-f91b-4e1b-bf77-88fad711e96d  
content-type: application/json