@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=bookings

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYzQ1YjQ4Ni0xMTU0LTRmM2QtYTgxNy1kOWEwZGNlY2E3MTYiLCJpYXQiOjE2NjA1NzgxMzMsImV4cCI6MTY2MDU4NTMzM30.X_Y-TfKiF_-GeoEOZwiE2fgV5lLNJikPTit4JaeTLPg


### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=5&skip=0&include=additionalServiceItems,customer&orderBy=createdAt
content-type: application/json
authorization: Bearer {{ACCESS_TOKEN}}


### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?include=additionalServiceItems,customer,vehicle    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "customerId": "e6dca990-7f93-4bbf-9d46-3604de7dbcbd",
    "vehicleId": "c68b5675-4224-4810-a20c-21a9c622d146",
    "from": "2022-07-13T17:58:37.493Z",
    "to": "2022-08-13T17:58:37.493Z",
    "duration": 30,
    "notes": "Do not forget to bring your keys",
    "additionalServiceItems": [
        {
            // Charge Battery id
            "serviceId": "84f672d4-fec1-4efe-906d-52be2b836260",
            "quantity": 5,
            "discount": 0
        },
        {
            // Premium polish id
            "serviceId": "5c527983-0753-4685-9870-6b54da397c2a",
            "quantity": 5,
            "discount": 0
        }
    ]
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/76d038e4-698a-4a92-bf78-d04d5add6bec
    ?include=bookings    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "firstName": "John Update",
    "lastName": "Doe Update",
    "phone": "123456789444",
    "address": "123 Main St"
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/f202a506-f91b-4e1b-bf77-88fad711e96d  
content-type: application/json