@BASE_URL=http://localhost:3002
@API_VERSION=v1

### find many customers
GET {{BASE_URL}}/{{API_VERSION}}/api/customers
    ?take=1&skip=0&include=bookings&orderBy=createdAt
content-type: application/json



### Create a new customer
POST {{BASE_URL}}/{{API_VERSION}}/api/customers
    ?include=bookings    
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@dfd.com",
    "phone": "123456789",
    "address": "123 Main St"
}