@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=customers

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTNjYmRmMy1jMThlLTQzMjUtYmI3My1jMDgyMTBhNmRlN2YiLCJpYXQiOjE2NjA1NjUzNjcsImV4cCI6MTY2MDU3MjU2N30.lHcC42pffgQPO1cgyZtRwHR1FRP5AuAnyihaxEFuLko

### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=2&skip=0&include=bookings&orderBy=createdAt
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}



### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?include=bookings    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@a.com",
    "phone": "123456789",
    "address": "123 Main St"
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/edb54b27-b7ca-4571-b984-b02efb193172
    ?include=bookings    
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "firstName": "John Update",
    "lastName": "Doe Update",
    "phone": "123456789444",
    "address": "123 Main St"
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/3091f188-2e9d-40d2-a30d-e6cc840f91f5
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}