@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=invoices

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjFkZGViMC04MWE5LTRhMmMtODQ2MC01YTk5N2QwZjk3ZTQiLCJpYXQiOjE2NjA1NDczODYsImV4cCI6MTY2MDU1NDU4Nn0.lHlggh-m4lSqxHwRngLcEP52IjB9MibHXV86qryykr8

### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?include=customer,booking,payment
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "bookingId": "ec6208f5-7b0c-48e1-a70b-aebd817a0a7c",
    "customerId": "f927f9df-1a8f-4ab4-8843-a8fa853615f4"
}

### pay invoice
PATCH  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/d947aa89-02cb-4291-80ca-73c8e72b2914/pay
    ?include=customer,booking,payment
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "amount": 4500,
    "paidBy": "Mr.Ok"
}