@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=invoices

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTNjYmRmMy1jMThlLTQzMjUtYmI3My1jMDgyMTBhNmRlN2YiLCJpYXQiOjE2NjA1NTY0MTUsImV4cCI6MTY2MDU2MzYxNX0.yDGyG2Ej-2njAF-vA83x3akFe3aIpSy9sEDMJkOclTE

### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?include=customer,booking,payment
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "bookingId": "58102e2b-78db-4b6b-8085-0bfb9a7495f1",
    "customerId": "edb54b27-b7ca-4571-b984-b02efb193172"
}

### pay invoice
PATCH  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/d947aa89-02cb-4291-80ca-73c8e72b2914/pay
    ?include=customer,booking,payment
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "amount": 4500,
    "paidBy": "Mr.Ok"
}