@BASE_URL=http://localhost:3002
@API_VERSION=v1

### find many services
GET {{BASE_URL}}/{{API_VERSION}}/api/services
    ?take=1&skip=0&include=bookings&orderBy=createdAt
content-type: application/json



### Create a new service
POST {{BASE_URL}}/{{API_VERSION}}/api/services  
content-type: application/json

{
    "name": "New Service",
    "price": 4500,
    "description": "New Service Description"
}



### update service from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/services/c9642146-556a-4133-8756-20d04c1e313e
    ?include=bookings    
content-type: application/json

{
    "name": "New Service Update",
    "price": 4550,
    "description": "New Service Description Update"    
}


### delete customer from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/services/f202a506-f91b-4e1b-bf77-88fad711e96d  
content-type: application/json