@BASE_URL=http://localhost:3002
@API_VERSION=v1

@MODEL=services

@ACCESS_TOKEN=

### find many model
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=1&skip=0&include=bookings&orderBy=createdAt
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}



### Create a new model
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}  
content-type: application/json

{
    "name": "New Service",
    "price": 4500,
    "description": "New Service Description"
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/c9642146-556a-4133-8756-20d04c1e313e
    ?include=bookings    
content-type: application/json

{
    "name": "New Service Update",
    "price": 4550,
    "description": "New Service Description Update"    
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/c9642146-556a-4133-8756-20d04c1e313e
content-type: application/json