@BASE_URL=http://localhost:3002
@API_VERSION=v1
@MODEL=users

### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=2&skip=0&include=roles
content-type: application/json



### Create a new
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}  
    ?include=roles
content-type: application/json

{
    "name": "John Doe",
    "username": "fsafsd",
    "password": "password",
    "confirmPassword": "password",
    "roleIds": ["af06802c-8ab1-48d2-af91-6104cfeab150"]
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/af06802c-8ab1-48d2-af91-6104cfeab150
    ?include=roles   
content-type: application/json

{
    "email": "test@tesss.com",
    "password": "newpassword"
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/a8a6f4b5-6719-4ecf-8161-42ac158e6d59
content-type: application/json