@BASE_URL=http://localhost:3002
@API_VERSION=v1
@MODEL=vehicles

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTNjYmRmMy1jMThlLTQzMjUtYmI3My1jMDgyMTBhNmRlN2YiLCJpYXQiOjE2NjA1NTg3ODMsImV4cCI6MTY2MDU2NTk4M30.3bMvBTcp2HNJV1Ghtjr0Det-8QN_xnefaCfy-RSt5w0

### find many
GET {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}
    ?take=1&skip=0&include=category,customer&orderBy=createdAt
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}



### Create a new
POST {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}  
    ?include=category,customer
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "plateNumber": "7A-123-456",
    "customerId": "edb54b27-b7ca-4571-b984-b02efb193172",
    "description": "New Vehicle Description"
}



### update model from given id
PATCH {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/885e36ec-9646-4055-b576-e3b9ac423253
    ?include=category,customer   
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "plateNumber": "7A-123-456",
    "description": "New Vehicle Description"  
}


### delete model from given id
DELETE  {{BASE_URL}}/{{API_VERSION}}/api/{{MODEL}}/885e36ec-9646-4055-b576-e3b9ac423253
content-type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}